### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by MihinMUD** [ali3re/minetest-auto-installer#1]

**Comment by MihinMUD** [comment]
Hi
:)

**Comment by MihinMUD** [comment]
Its k if i m annoying you just had to tell me 
I sayed you i will try to fix it

**Comment by MihinMUD** [comment]
I m still your best friend right?  anywways you are my best friend

**Comment by ali3re** [comment]
mihin i want to leave pls let me be it

**Comment by MihinMUD** [comment]
no please

**Comment by MihinMUD** [comment]
i dont let you anyways
think about the advatage

**Comment by MihinMUD** [comment]
you wont get any advantage

**Comment by MihinMUD** [comment]
just think about it

**Comment by MihinMUD** [comment]
and pelase unblock me it is the best thing you can ever do
